apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: spring-boot-cities-service
      name: spring-boot-cities-service
    name: spring-boot-cities-service
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: spring-boot-cities-service:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: openshift
        uri: https://github.com/Sufyaan-Kazi/spring-boot-cities-service.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-java:latest
          namespace: spring-boot-cities-service
      type: Source
    triggers:
    - github:
        secret: 1RyU_rq6JubmiOa-TNcI
      type: GitHub
    - generic:
        secret: VDXN6FlExofdeJCnutil
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      name: spring-boot-cities-service
      template: mysql-persistent-template
    name: mysql
  spec:
    replicas: 1
    selector:
      name: mysql
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: mysql
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mysql
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mysql
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: mysql
          - name: MYSQL_DATABASE
            value: cities
          image: centos/mysql-57-centos7@sha256:54444d4e5c358aeb276b53889a9d714b410364b78fb5ca98791589ba0875762a
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: mysql-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:5.7
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: spring-boot-cities-service
      name: spring-boot-cities-service
    name: spring-boot-cities-service
  spec:
    replicas: 1
    selector:
      app: spring-boot-cities-service
      deploymentconfig: spring-boot-cities-service
      name: spring-boot-cities-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: spring-boot-cities-service
          deploymentconfig: spring-boot-cities-service
          name: spring-boot-cities-service
      spec:
        containers:
        - env:
          - name: APP_OPTIONS
          - name: DATABASE_SERVICE_NAME
            value: mysql
          - name: JVM_OPTIONS
            value: -Dspring.profiles.active=oshift
          - name: MYSQL_DATABASE
            value: cities
          - name: MYSQL_PASSWORD
            value: mysqlpassword
          - name: MYSQL_ROOT_PASSWORD
            value: mysqlrootpassword
          - name: MYSQL_USER
            value: mysqluser
          image: 172.30.1.1:5000/spring-boot-cities-service/spring-boot-cities-service@sha256:4ce38a98bda90afb639072a5b14c9478d95042e8c8b34819c15af5ac95f812db
          imagePullPolicy: Always
          name: spring-boot-cities-service
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot-cities-service
        from:
          kind: ImageStreamTag
          name: spring-boot-cities-service:latest
          namespace: spring-boot-cities-service
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: spring-boot-cities-service
      name: spring-boot-cities-service
    name: spring-boot-cities-service
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/spring-boot-cities-service/spring-boot-cities-service:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      name: spring-boot-cities-service
      template: mysql-persistent-template
    name: mysql
  spec:
    ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: spring-boot-cities-service
      name: spring-boot-cities-service
    name: spring-boot-cities-service
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-boot-cities-service
      deploymentconfig: spring-boot-cities-service
      name: spring-boot-cities-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  data:
    database-password: bXlzcWxwYXNzd29yZA==
    database-root-password: bXlzcWxyb290cGFzc3dvcmQ=
    database-user: bXlzcWx1c2Vy
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      name: spring-boot-cities-service
      template: mysql-persistent-template
    name: mysql
  type: Opaque
kind: List
metadata: {}
