---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: thelab/openshift-client

inputs:
  - name: cities-service

run:
  path: "cities-service/ci/scripts/createProject.sh"
