---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: cities-service

run:
  path: "cities-service/ci/scripts/createServices.sh"
  args: ["-a", "api.run.haas-35.pez.pivotal.io", "-u", "skazi", "-p", "letmein", "-o", "skazi", "s", "cities"]
