---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: latest

inputs:
  - name: cities-service

run:
  path: "cities-service/ci/tasks/createServices.sh"
