---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli

inputs:
  - name: cities-service
  - name: resource-version
  - name: build

outputs:
  - name: deployOutputs

run:
  path: "cities-service/ci/scripts/deployToPCF.sh"
