---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: latest

inputs:
  - name: cities-service

run:
  path: "cities-service/ci/scripts/prepPCFSpace.sh"
