---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: cities-service

outputs:
  - name: build

run:
  path: "cities-service/ci/scripts/package.sh"
