---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java

inputs:
  - name: cities-service

outputs:
  - name: .gradle

run:
  path: "cities-service/gradlew"
  args: ["--build-file", "cities-service/build.gradle", "test"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
