---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java

inputs:
  - name: spring-boot-cities-service

run:
  path: "spring-boot-cities-service/gradlew"
  args: ["--build-file", "spring-boot-cities-service/build.gradle", "test"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
