git-uri-bump-semver: https://github.com/skazi-pivotal/spring-boot-cities-service/tree/version
CF_API: https://api.run.haas-35.pez.pivotal.io
CF_USERNAME: skazi
CF_PASSWORD: letmein
CF_ORG: skazi
CF_SPACE: cities
CF_SSL: --skip-ssl-validation
APPNAME: cities-service
SERVICE_NAME: MyDB
