---
resources:
- name: cities-service
  type: git
  source:
    uri: {{git-uri}}
  check_every: 8s

- name: resource-version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri}}
    branch: version
    file: version

- name: deploy-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USERNAME}}
    password: {{CF_PASSWORD}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true

jobs:
- name: testSrc
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    trigger: true
  - task: test
    file: cities-service/ci/tasks/test.yml

- name: prepPCFSpace
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    trigger: true
  - task: prepPCFSpace
    file: cities-service/ci/tasks/prepPCFSpace.yml
    params:
      api: {{CF_API}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}
      SERVICE_NAME: {{SERVICE_NAME}}

- name: deployApp
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    trigger: true
    passed: [testSrc, prepPCFSpace]
  - get: resource-version
    params:
      bump: minor
  - task: package
    file: cities-service/ci/tasks/package.yml
    params:
      APPNAME: {{APPNAME}}
  - put: deploy-app
    params:
      manifest: cities-service/manifest.yml
      path: build/cities-service-1.0.jar
      current_app_name: {{APPNAME}}

- name: testAppOnPCF
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    trigger: true
    passed: [deployApp]
  - task: test
    file: cities-service/ci/tasks/testAppOnPCF.yml
    params:
      api: {{CF_API}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}
