---
resources:
- name: cities-service
  type: git
  source:
    uri: {{git-uri}}

- name: resource-version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    initial_version: 0.0.0
    uri: {{GIT-SSH-URI}}
    private_key: {{GIT_KEY}}
    git_user: {{GIT_USER}}

- name: deployToPCF
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USERNAME}}
    password: {{CF_PASSWORD}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true

jobs:
- name: testSrc
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    trigger: true
  - task: test
    file: cities-service/ci/tasks/test.yml

- name: createPCFSpace
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    trigger: true
  - task: createPCFSpace
    file: cities-service/ci/tasks/createPCFSpace.yml
    params:
      CREATE_FRESH_SPACE: {{CREATE_FRESH_SPACE}}
      api: {{CF_API}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}

- name: prepPCFSpace
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    passed:
      - createPCFSpace
    trigger: true
  - task: prepPCFSpace
    file: cities-service/ci/tasks/prepPCFSpace.yml
    params:
      api: {{CF_API}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}
      SERVICE_NAME: {{SERVICE_NAME}}

- name: packageAndDeploy
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    passed:
      - testSrc
      - prepPCFSpace
    trigger: true
  - get: resource-version
    params:
      bump: patch
  - task: package
    file: cities-service/ci/tasks/package.yml
    params:
      APPNAME: {{APPNAME}}
  - put: resource-version
    params: {file: resource-version/number}
  - task: amendManifest
    file: cities-service/ci/tasks/amendManifest.yml
    params:
      APPNAME: {{APPNAME}}
      username: {{CF_USERNAME}}
  - put: deployToPCF
    params:
      manifest: output/manifest.yml
      path: build/cities-service-1.0.jar
      current_app_name: {{APPNAME}}
  - task: addVersionInfo
    file: cities-service/ci/tasks/addVersionInfo.yml
    params:
      api: {{CF_API}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}

- name: testAppOnPCF
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    passed:
      - packageAndDeploy
    trigger: true
  - task: test
    file: cities-service/ci/tasks/testAppOnPCF.yml
    params:
      api: {{CF_API}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}
      username: {{CF_USERNAME}}
      password: {{CF_PASSWORD}}
      ssl: {{CF_SSL}}
      APPNAME: {{APPNAME}}
