---
resources:
- name: cities-service
  type: git
  source:
    uri: {{git-uri}}
    branch: openshift

jobs:
- name: testSrc
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    trigger: true
  - task: test
    file: cities-service/ci/tasks/test.yml

- name: packageNPush
  build_logs_to_retain: 5
  plan:
  - get: cities-service
    passed:
      - testSrc
    trigger: true
  - task: package
    file: cities-service/ci/tasks/package.yml
    params:
      APPNAME: {{APPNAME}}
